# Generated by Django 6.0.5 on 2026-05-24 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0009_academia_login_imagen_alter_academia_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Módulo/Clase')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción General (Opcional)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_multimedia', to='academias.academia')),
            ],
        ),
        migrations.CreateModel(
            name='VideoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Video')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Video')),
                ('youtube_id', models.CharField(max_length=100, verbose_name='YouTube Video ID')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='multimedia.moduloclase')),
            ],
        ),
    ]
