# Generated by Django 5.2.14 on 2026-07-23 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0014_academia_razon_social_academia_representante_legal_and_more'),
        ('finanzas', '0002_gasto_es_deducible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(help_text='Se usará como contraseña inicial y para soportes de egreso.', max_length=50, verbose_name='Documento de Identidad / NIT')),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_pago', models.CharField(choices=[('POR_CLASE', 'Pago individual por clase dictada'), ('MENSUAL', 'Pago mensual acumulado (Planilla / Orden de Pago)')], default='POR_CLASE', max_length=20)),
                ('tarifa_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa base por clase')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academias.academia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPagoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_periodo', models.DateField(help_text='Mes de referencia (Ej: 2026-07-01 representa Julio)')),
                ('cantidad_clases', models.IntegerField(default=0, verbose_name='Total clases dictadas')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('GENERADA', 'Generada (Pendiente revisión del profesor)'), ('REVISAR', 'En revisión (El profesor dejó comentarios)'), ('APROBADA_PROFE', 'Aprobada por el profe (Lista para que Admin pague)'), ('PAGADA', 'Pagada e ingresada en Finanzas')], default='GENERADA', max_length=25)),
                ('comentarios_profe', models.TextField(blank=True, help_text="Observaciones si el profesor le da clic a 'Revisar'", null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academias.academia')),
                ('gasto_asociado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_pago_profe', to='finanzas.gasto')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_pago', to='profesores.profesor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
