# Generated by Django 5.2.14 on 2026-09-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='documento_identidad',
            field=models.CharField(help_text='Documento para soportes de egreso; nunca se utiliza como contraseña.', max_length=50, verbose_name='Documento de Identidad / NIT'),
        ),
    ]
