# Generated by Django 6.0.5 on 2026-05-24 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0002_alter_academia_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250)),
                ('fecha', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('precio_preventa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_puerta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datos_pago_instrucciones', models.TextField(default='Realiza tu transferencia a la cuenta de ahorros Bancolombia N° 123-456... y adjunta el comprobante abajo.')),
                ('terminos_condiciones', models.TextField(default='Al adquirir esta entrada aceptas las políticas de ingreso de la academia. No se realizan devoluciones.')),
                ('estado', models.CharField(choices=[('REGISTRO_ONLINE', 'Registro Online Abierto'), ('REGISTRO_PUERTA', 'Solo Registro en Puerta'), ('FINALIZADO', 'Evento Finalizado y Cerrado')], default='REGISTRO_ONLINE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_academia', to='academias.academia')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('academia', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_codigo', models.CharField(max_length=50)),
                ('fecha_caducidad', models.DateTimeField()),
                ('limite_usos', models.PositiveIntegerField(default=100)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('precio_especial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_descuento', to='eventos.evento')),
            ],
            options={
                'unique_together': {('evento', 'nombre_codigo')},
            },
        ),
        migrations.CreateModel(
            name='GastoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_evento', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=50, unique=True)),
                ('comprador_nombre', models.CharField(max_length=150)),
                ('comprador_correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('comprador_telefono', models.CharField(max_length=30)),
                ('cantidad_entradas', models.PositiveIntegerField(default=1)),
                ('precio_unitario_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia / Nequi'), ('TARJETA', 'Tarjeta de Crédito/Débito')], default='TRANSFERENCIA', max_length=20)),
                ('origen', models.CharField(choices=[('ONLINE', 'Inscripción Web'), ('PUERTA', 'Vendido en Taquilla / Puerta')], default='ONLINE', max_length=10)),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes_eventos/')),
                ('revisado_por_admin', models.BooleanField(default=True)),
                ('ingresado_puerta', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('codigo_descuento_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.codigodescuento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos_evento', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ingresado', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_qr', to='eventos.reciboevento')),
            ],
        ),
    ]
