# Generated by Django 6.0.5 on 2026-05-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaqr',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrs_eventos/'),
        ),
    ]
