# Generated by Django 6.0.5 on 2026-05-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_entradaqr_imagen_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='banners_eventos/', verbose_name='Afiche del Evento (Sugerido 1:1)'),
        ),
    ]
