# Generated by Django 6.0.5 on 2026-05-24 19:27

import apps.eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.eventos.models.ruta_banners_academia, verbose_name='Afiche del Evento (Sugerido 1:1)'),
        ),
    ]
