# Generated by Django 6.0.5 on 2026-05-29 18:57

import apps.eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='datos_pago_instrucciones',
        ),
        migrations.AddField(
            model_name='evento',
            name='acepta_banco_manual',
            field=models.BooleanField(default=False, verbose_name='Habilitar Transferencia Bancaria Directa'),
        ),
        migrations.AddField(
            model_name='evento',
            name='acepta_nequi_daviplata',
            field=models.BooleanField(default=False, verbose_name='Habilitar Nequi/Daviplata/Llave'),
        ),
        migrations.AddField(
            model_name='evento',
            name='acepta_tarjetas_online',
            field=models.BooleanField(default=False, verbose_name='Habilitar Pago Automático con Tarjeta'),
        ),
        migrations.AddField(
            model_name='evento',
            name='datos_banco_manual',
            field=models.TextField(blank=True, help_text='Inyecta: Banco, Tipo de cuenta, Número, Cédula/NIT titular.', null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='deuda_online_calculada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='deuda_puerta_calculada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='numero_nequi_daviplata',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número o Texto de la Llave'),
        ),
        migrations.AddField(
            model_name='evento',
            name='online_liquidado',
            field=models.BooleanField(default=False, verbose_name='¿Comisión Online Pagada a la Plataforma?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='puerta_liquidado',
            field=models.BooleanField(default=False, verbose_name='¿Comisión Puerta Pagada a la Plataforma?'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.eventos.models.ruta_banners_academia),
        ),
    ]
