# Generated by Django 6.0.5 on 2026-05-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_remove_evento_datos_pago_instrucciones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradaqr',
            old_name='fecha_ingreso',
            new_name='fecha_ultimo_ingreso',
        ),
        migrations.RemoveField(
            model_name='entradaqr',
            name='ingresado',
        ),
        migrations.AddField(
            model_name='entradaqr',
            name='asistencias_consumidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entradaqr',
            name='asistencias_permitidas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evento',
            name='cantidad_dias',
            field=models.PositiveIntegerField(default=1, help_text='Total de días del evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='es_multidias',
            field=models.BooleanField(default=False, verbose_name='¿Es un evento de varios días?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='permite_compra_por_dia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FasePreventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fase', models.CharField(max_length=50)),
                ('fecha_limite', models.DateTimeField()),
                ('precio_full', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases_preventa', to='eventos.evento')),
            ],
        ),
    ]
