# Generated by Django 5.2.14 on 2026-06-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_rename_fecha_ingreso_entradaqr_fecha_ultimo_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigodescuento',
            name='precio_especial_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento (Por 1 Día)'),
        ),
    ]
