# Generated by Django 5.2.14 on 2026-06-12 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_codigodescuento_precio_especial_dia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fasepreventa',
            options={'ordering': ['fecha_limite']},
        ),
        migrations.AlterField(
            model_name='fasepreventa',
            name='fecha_limite',
            field=models.DateTimeField(help_text='Hasta cuándo estará activa esta fase'),
        ),
        migrations.AlterField(
            model_name='fasepreventa',
            name='precio_full',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TipoPase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accesos_permitidos', models.PositiveIntegerField(default=1, help_text='¿Cuántos días/veces puede escanear su QR con este pase?')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pases_personalizados', to='eventos.evento')),
            ],
            options={
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='PrecioFasePase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_pases', to='eventos.fasepreventa')),
                ('pase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_fases', to='eventos.tipopase')),
            ],
            options={
                'unique_together': {('fase', 'pase')},
            },
        ),
    ]
