# Generated by Django 5.2.14 on 2026-06-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_alter_fasepreventa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tiene_fases_fechas',
            field=models.BooleanField(default=False, verbose_name='¿Tiene múltiples fechas de pago (Preventas)?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tiene_pases_personalizados',
            field=models.BooleanField(default=False, verbose_name='¿Tiene varios tipos de entrada/pases?'),
        ),
    ]
