# Generated by Django 5.2.14 on 2026-06-12 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_evento_tiene_fases_fechas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciboevento',
            name='fase_preventa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos', to='eventos.fasepreventa'),
        ),
        migrations.AddField(
            model_name='reciboevento',
            name='tipo_pase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos', to='eventos.tipopase'),
        ),
    ]
