# Generated by Django 5.2.14 on 2026-06-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_reciboevento_fase_preventa_reciboevento_tipo_pase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='precio_preventa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='precio_puerta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
