# Generated by Django 5.2.14 on 2026-06-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_alter_evento_precio_preventa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciboevento',
            name='anulado',
            field=models.BooleanField(default=False, verbose_name='¿Recibo Anulado?'),
        ),
    ]
