# Generated by Django 5.2.14 on 2026-06-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_reciboevento_anulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='enlace_externo',
            field=models.URLField(blank=True, help_text="Si se llena, el botón 'Conseguir Tickets' abrirá esta URL en otra pestaña.", max_length=500, null=True, verbose_name='Enlace de Registro Externo'),
        ),
    ]
