# Generated by Django 5.2.14 on 2026-07-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_evento_enlace_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigodescuento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Código Activo?'),
        ),
    ]
