# Generated by Django 5.2.14 on 2026-08-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_codigodescuento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigodescuento',
            name='pase_aplicable',
            field=models.ForeignKey(blank=True, help_text='Si se deja en blanco, el cupón aplica para todo el evento. Si se selecciona un pase, solo servirá para ese pase.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupones_asociados', to='eventos.tipopase'),
        ),
    ]
