# Generated by Django 5.2.14 on 2026-09-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_codigodescuento_pase_aplicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopase',
            name='qrs_por_pase',
            field=models.PositiveIntegerField(default=1, help_text='1 = Individual, 2 = Pareja. Define cuántos QRs se generan al comprar 1 unidad.', verbose_name='Personas por Pase'),
        ),
    ]
