# Generated by Django 5.2.14 on 2026-09-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_tipopase_qrs_por_pase'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Déjalo en blanco para heredar la ciudad principal de tu academia. Escribe otra ciudad (Ej: Medellín) si el evento será en otra ubicación.', max_length=100, null=True, verbose_name='Ciudad del Evento'),
        ),
    ]
