# Generated by Django 5.2.14 on 2026-09-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_evento_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Bogotá', 'Bogotá'), ('Medellín', 'Medellín'), ('Cali', 'Cali'), ('Barranquilla', 'Barranquilla'), ('Bucaramanga', 'Bucaramanga'), ('Pereira', 'Pereira'), ('Manizales', 'Manizales'), ('Armenia', 'Armenia'), ('Cartagena', 'Cartagena'), ('Villavicencio', 'Villavicencio'), ('Ibagué', 'Ibagué'), ('Otra', 'Otra ciudad...')], default='Bogotá', help_text='Selecciona la ciudad física del evento. Si se deja en blanco, heredará la de tu academia.', max_length=50, null=True, verbose_name='Ciudad del Evento'),
        ),
    ]
