# Generated by Django 5.2.14 on 2026-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_colaboradorevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopase',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Pase Activo?'),
        ),
    ]
