# Generated by Django 5.2.14 on 2026-09-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_tipopase_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='connect_dya_finances',
            field=models.BooleanField(default=False, verbose_name='Conectar con finanzas Duane y Aleja'),
        ),
        migrations.AddField(
            model_name='evento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
