# Generated by Django 5.2.14 on 2026-09-29 04:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_evento_connect_dya_finances_evento_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaqr',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciboevento',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciboevento',
            name='payment_status',
            field=models.CharField(choices=[('LEGACY', 'Histórico (verificación no certificada)'), ('PENDING', 'Pendiente de aprobación'), ('CONFIRMED', 'Pago confirmado'), ('CANCELLED', 'Anulado (no implica devolución)'), ('REFUNDED', 'Devolución registrada'), ('REVIEW', 'En revisión')], default='LEGACY', max_length=16),
        ),
        migrations.AlterField(
            model_name='reciboevento',
            name='payment_status',
            field=models.CharField(choices=[('LEGACY', 'Histórico (verificación no certificada)'), ('PENDING', 'Pendiente de aprobación'), ('CONFIRMED', 'Pago confirmado'), ('CANCELLED', 'Anulado (no implica devolución)'), ('REFUNDED', 'Devolución registrada'), ('REVIEW', 'En revisión')], default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='reciboevento',
            name='price_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reciboevento',
            name='registration_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipopase',
            name='admissions_per_unit',
            field=models.PositiveIntegerField(blank=True, help_text='Unidades comerciales por pase. Vacío conserva acceso legacy sin generar cargos SaaS.', null=True),
        ),
        migrations.AlterField(
            model_name='reciboevento',
            name='revisado_por_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('commercial_unit', models.BooleanField(default=False)),
                ('access_limit', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='eventos.reciboevento')),
            ],
        ),
        migrations.AddField(
            model_name='entradaqr',
            name='admission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credential', to='eventos.admission'),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_code', models.UUIDField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('day', models.DateField()),
                ('result', models.CharField(max_length=24)),
                ('request_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='eventos.entradaqr')),
            ],
        ),
        migrations.CreateModel(
            name='EventRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_records', to='eventos.reciboevento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(fields=('receipt', 'ordinal'), name='admission_receipt_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(condition=models.Q(('result', 'SUCCESS')), fields=('credential', 'day'), name='checkin_once_per_day'),
        ),
    ]
