# Generated by Django 5.2.14 on 2026-09-29 04:10

import apps.academias.private_media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_durable_event_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaqr',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, storage=apps.academias.private_media.PrivateStorage(), upload_to='qrs_eventos/', validators=[apps.academias.private_media.validate_private_upload]),
        ),
        migrations.AlterField(
            model_name='reciboevento',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, storage=apps.academias.private_media.PrivateStorage(), upload_to='comprobantes_eventos/', validators=[apps.academias.private_media.validate_private_upload]),
        ),
    ]
