# Generated by Django 6.0.5 on 2026-05-23 00:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0002_alter_academia_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='Cédula / TI')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo / Al Día'), ('INACTIVO', 'Inactivo / Sin Plan')], default='INACTIVO', max_length=15)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrs_estudiantes/')),
                ('token_asistencia', models.CharField(editable=False, max_length=64, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academias.academia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($ COP)')),
                ('duracion_dias', models.PositiveIntegerField(default=30, verbose_name='Duración en Días')),
                ('clases_totales', models.PositiveIntegerField(default=8, verbose_name='Clases Incluidas')),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academias.academia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InscripcionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField()),
                ('clases_restantes', models.PositiveIntegerField()),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academias.academia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='planes_estudiantes.estudiante')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='planes_estudiantes.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
