# Generated by Django 5.2.14 on 2026-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0013_academia_es_solo_eventos'),
        ('planes_estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='identificacion',
            field=models.CharField(max_length=20, verbose_name='Cédula / TI'),
        ),
        migrations.AlterUniqueTogether(
            name='estudiante',
            unique_together={('academia', 'identificacion')},
        ),
    ]
