# Generated by Django 5.2.14 on 2026-09-29 04:10

import apps.academias.private_media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_estudiantes', '0002_alter_estudiante_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=apps.academias.private_media.PrivateStorage(), upload_to='qrs_estudiantes/', validators=[apps.academias.private_media.validate_private_upload]),
        ),
    ]
