# Generated by Django 5.2.14 on 2026-09-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_estudiantes', '0004_account_setup_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionplan',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
