# Generated by Django 6.0.5 on 2026-05-28 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0009_academia_login_imagen_alter_academia_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual (COP)')),
                ('max_estudiantes', models.IntegerField(default=50, verbose_name='Límite de Estudiantes')),
                ('permite_multimedia', models.BooleanField(default=False, verbose_name='Acceso a Módulo Multimedia')),
                ('permite_finanzas', models.BooleanField(default=True, verbose_name='Acceso a Módulo Finanzas/DIAN')),
                ('permite_asistencias_qr', models.BooleanField(default=True, verbose_name='Acceso a Escáner QR')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuscripcionAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo / Al Día'), ('SUSPENDIDO', 'Suspendido por Falta de Pago'), ('PRUEBA', 'Período de Prueba')], default='PRUEBA', max_length=20)),
                ('bloqueo_manual_multimedia', models.BooleanField(default=False, verbose_name='Bloquear Multimedia Manualmente')),
                ('bloqueo_manual_finanzas', models.BooleanField(default=False, verbose_name='Bloquear Finanzas Manualmente')),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('academia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_saas', to='academias.academia')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academias_inscritas', to='saas_core.plansaas')),
            ],
        ),
    ]
