# Generated by Django 6.0.5 on 2026-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansaas',
            name='permite_eventos',
            field=models.BooleanField(default=False, verbose_name='Acceso a Módulo Eventos'),
        ),
        migrations.AddField(
            model_name='suscripcionacademia',
            name='bloqueo_manual_asistencias',
            field=models.BooleanField(default=False, verbose_name='Bloquear Asistencias Manualmente'),
        ),
        migrations.AddField(
            model_name='suscripcionacademia',
            name='bloqueo_manual_eventos',
            field=models.BooleanField(default=False, verbose_name='Bloquear Eventos Manualmente'),
        ),
    ]
