# Generated by Django 6.0.5 on 2026-05-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0002_plansaas_permite_eventos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcionacademia',
            name='dias_regalados_prueba',
            field=models.IntegerField(default=15, verbose_name='Días autorizados para el Plan Gratis'),
        ),
        migrations.AddField(
            model_name='suscripcionacademia',
            name='ya_uso_prueba_gratis',
            field=models.BooleanField(default=False, verbose_name='¿Ya consumió su beneficio de prueba gratis?'),
        ),
    ]
