# Generated by Django 6.0.5 on 2026-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0003_suscripcionacademia_dias_regalados_prueba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansaas',
            name='tipo_cobro',
            field=models.CharField(choices=[('MENSUAL', 'Suscripción Mensual / Días Fijos'), ('POR_EVENTO', 'Plan Transaccional Pure Event (Mensualidad $0)')], default='MENSUAL', max_length=15),
        ),
    ]
