# Generated by Django 6.0.5 on 2026-05-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0004_plansaas_tipo_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansaas',
            name='es_cuenta_partner_gratis',
            field=models.BooleanField(default=False, verbose_name='Cuenta Aliada / Gratis Permanente (No cobra plan ni comisiones)'),
        ),
    ]
