# Generated by Django 6.0.5 on 2026-05-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0005_plansaas_es_cuenta_partner_gratis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansaas',
            name='es_cuenta_partner_gratis',
        ),
        migrations.AddField(
            model_name='suscripcionacademia',
            name='es_cuenta_partner_gratis',
            field=models.BooleanField(default=False, verbose_name='Cuenta Aliada / Gratis Permanente (No cobra plan ni comisiones)'),
        ),
    ]
