# Generated by Django 6.0.5 on 2026-05-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0006_remove_plansaas_es_cuenta_partner_gratis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansaas',
            name='permite_estudiantes',
            field=models.BooleanField(default=True, verbose_name='Acceso a Módulo Estudiantes'),
        ),
        migrations.AddField(
            model_name='suscripcionacademia',
            name='bloqueo_manual_estudiantes',
            field=models.BooleanField(default=False, verbose_name='Bloquear Estudiantes Manualmente'),
        ),
    ]
