# Generated by Django 5.2.14 on 2026-05-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0007_plansaas_permite_estudiantes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(help_text='Bootstrap Icon', max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(max_length=200)),
                ('subtitulo_principal', models.TextField()),
                ('boton_principal_texto', models.CharField(max_length=100)),
                ('boton_principal_url', models.CharField(max_length=300)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('mostrar_capturas', models.BooleanField(default=True)),
                ('mostrar_faq', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='landing/screenshots/')),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TestimonioLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('academia', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='landing/testimonios/')),
                ('comentario', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
