# Generated by Django 5.2.14 on 2026-05-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0008_beneficiolanding_faqlanding_landingpageconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('youtube_url', models.URLField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
