# Generated by Django 5.2.14 on 2026-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0009_videolanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansaas',
            name='permite_tienda',
            field=models.BooleanField(default=False, verbose_name='Acceso a Módulo Tienda/POS'),
        ),
        migrations.AddField(
            model_name='suscripcionacademia',
            name='bloqueo_manual_tienda',
            field=models.BooleanField(default=False, verbose_name='Bloquear Tienda Manualmente'),
        ),
    ]
