# Generated by Django 5.2.14 on 2026-06-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0010_plansaas_permite_tienda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPagoGlobalSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_metodo', models.CharField(choices=[('BANCO', 'Cuenta Bancaria Tradicional'), ('NEQUI', 'Plataforma Nequi (Número de celular)'), ('DAVIPLATA', 'Plataforma Daviplata (Número de celular)'), ('LLAVE', 'Llave Transfiya / Celular / Correo'), ('QR_DIRECTO', 'Código QR de Transferencia Directa')], default='NEQUI', max_length=20, verbose_name='Tipo de Canal de Pago')),
                ('nombre_proveedor', models.CharField(help_text='Ej: Bancolombia, Nequi, Davivienda, etc.', max_length=100, verbose_name='Entidad / Proveedor')),
                ('identificador_pago', models.CharField(help_text='El dato exacto que el cliente debe copiar para transferir.', max_length=150, verbose_name='Número de Cuenta / Celular / Llave')),
                ('titular', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titular de la cuenta (Opcional)')),
                ('documento_titular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula/NIT del Titular (Opcional)')),
                ('instrucciones_adicionales', models.TextField(blank=True, help_text="Mensaje instructivo (Ej: 'Una vez transferido, envía el pantallazo al WhatsApp 310...')")),
            ],
            options={
                'verbose_name': 'Configuración de Pago Global SaaS',
                'verbose_name_plural': 'Configuraciones de Pago Global SaaS',
            },
        ),
    ]
