# Generated by Django 5.2.14 on 2026-06-07 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0013_academia_es_solo_eventos'),
        ('saas_core', '0011_configpagoglobalsaas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePagoSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.FileField(upload_to='saas_comprobantes/%Y/%m/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado y Renovado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_pago', to='academias.academia')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saas_core.plansaas')),
            ],
            options={
                'verbose_name': 'Reporte de Pago SaaS',
                'verbose_name_plural': 'Reportes de Pago SaaS',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
