# Generated by Django 5.2.14 on 2026-06-07 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0014_academia_razon_social_academia_representante_legal_and_more'),
        ('saas_core', '0012_reportepagosaas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(default='TRANSFERENCIA/COMPROBANTE', max_length=50)),
                ('concepto', models.CharField(max_length=255)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos_pagados_saas', to='academias.academia')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.plansaas')),
            ],
            options={
                'verbose_name': 'Recibo de Ingreso SaaS',
                'verbose_name_plural': 'Recibos de Ingreso SaaS',
                'ordering': ['-fecha'],
            },
        ),
    ]
