# Generated by Django 5.2.14 on 2026-06-07 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0013_recibosaas'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('concepto', models.CharField(max_length=255, verbose_name='Descripción / Concepto')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='saas/gastos_comprobantes/')),
            ],
            options={
                'verbose_name': 'Gasto SaaS',
                'verbose_name_plural': 'Gastos SaaS',
                'ordering': ['-fecha'],
            },
        ),
    ]
