# Generated by Django 5.2.14 on 2026-06-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0014_gastosaas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcionacademia',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo / Al Día'), ('SUSPENDIDO', 'Suspendido por Falta de Pago'), ('PRUEBA', 'Período de Prueba')], default='SUSPENDIDO', max_length=20),
        ),
    ]
