# Generated by Django 5.2.14 on 2026-09-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0015_alter_suscripcionacademia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansaas',
            name='permite_calendario',
            field=models.BooleanField(default=False, verbose_name='Acceso a Módulo Calendario'),
        ),
        migrations.AddField(
            model_name='plansaas',
            name='permite_profesores',
            field=models.BooleanField(default=False, verbose_name='Acceso a Módulo Profesores/Nómina'),
        ),
        migrations.AddField(
            model_name='suscripcionacademia',
            name='bloqueo_manual_calendario',
            field=models.BooleanField(default=False, verbose_name='Bloquear Calendario Manualmente'),
        ),
        migrations.AddField(
            model_name='suscripcionacademia',
            name='bloqueo_manual_profesores',
            field=models.BooleanField(default=False, verbose_name='Bloquear Profesores Manualmente'),
        ),
    ]
