# Generated by Django 5.2.14 on 2026-09-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0016_plansaas_permite_calendario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcionacademia',
            name='comision_por_tiquete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión por Ticket (Eventos)'),
        ),
    ]
