# Generated by Django 5.2.14 on 2026-09-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0017_suscripcionacademia_comision_por_tiquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcionacademia',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo / Al Día'), ('MORA', 'En Mora (Período de Gracia)'), ('SUSPENDIDO', 'Suspendido por Falta de Pago'), ('PRUEBA', 'Período de Prueba')], default='SUSPENDIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='suscripcionacademia',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academias_inscritas', to='saas_core.plansaas'),
        ),
    ]
