# Generated by Django 5.2.14 on 2026-09-29 04:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0018_backfill_memberships'),
        ('saas_core', '0018_alter_suscripcionacademia_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=80)),
                ('action', models.CharField(max_length=80)),
                ('resource', models.CharField(max_length=120)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('academia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academias.academia')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DurableJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('DONE', 'Completado'), ('FAILED', 'Falló')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                ('academia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academias.academia')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'available_at'], name='job_ready_idx')],
            },
        ),
    ]
