# Generated by Django 5.2.14 on 2026-09-29 04:10

import apps.academias.private_media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0019_durable_event_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosaas',
            name='comprobante',
            field=models.FileField(blank=True, null=True, storage=apps.academias.private_media.PrivateStorage(), upload_to='saas/gastos_comprobantes/', validators=[apps.academias.private_media.validate_private_upload]),
        ),
        migrations.AlterField(
            model_name='reportepagosaas',
            name='comprobante',
            field=models.FileField(storage=apps.academias.private_media.PrivateStorage(), upload_to='saas_comprobantes/%Y/%m/', validators=[apps.academias.private_media.validate_private_upload]),
        ),
    ]
