# Generated by Django 5.2.14 on 2026-09-29 04:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0020_commercial_ledger'),
        ('eventos', '0023_private_supporting_documents'),
        ('saas_core', '0020_private_supporting_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('reference', models.CharField(db_index=True, max_length=150)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('INTERNAL', 'Interno / exento permanente'), ('COMPLIMENTARY', 'Acceso concedido sin cobro'), ('TRIAL', 'Prueba sin cobro automático'), ('PAID', 'Contrato comercial'), ('LEGACY', 'Histórico / pendiente de contratación')], default='LEGACY', max_length=20)),
                ('grant_until', models.DateTimeField(blank=True, null=True)),
                ('grant_features', models.JSONField(default=dict)),
                ('grant_reason', models.CharField(blank=True, max_length=255)),
                ('legacy_snapshot', models.JSONField(blank=True, default=dict)),
                ('automatic_charges_authorized', models.BooleanField(default=False)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('grace_days', models.PositiveSmallIntegerField(default=7)),
                ('suspend_after_days', models.PositiveSmallIntegerField(default=21)),
                ('retry_days', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_account', to='academias.academia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('interval_months', models.PositiveSmallIntegerField(default=1)),
                ('features', models.JSONField(default=dict)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='saas_core.plansaas')),
            ],
        ),
        migrations.CreateModel(
            name='EventFeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('PLAN', 'Plan'), ('TENANT', 'Academia'), ('EVENT', 'Evento')], max_length=10)),
                ('fixed_per_admission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=255)),
                ('academia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academias.academia')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventos.evento')),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saas_core.planversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('TRIAL', 'En prueba'), ('ACTIVE', 'Activa'), ('PAST_DUE', 'Pago pendiente / gracia'), ('LIMITED', 'Operación limitada'), ('SUSPENDED', 'Suspendida'), ('CANCELLED', 'Cancelada')], default='TRIAL', max_length=16)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(default='MANUAL', max_length=20)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=150)),
                ('provider_state', models.CharField(blank=True, max_length=40)),
                ('provider_customer_id', models.CharField(blank=True, max_length=150)),
                ('payment_method_ref', models.CharField(blank=True, max_length=150)),
                ('last_paid_period_end', models.DateTimeField(blank=True, null=True)),
                ('academia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_subscription', to='academias.academia')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.planversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderEventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='RECEIVED', max_length=20)),
                ('processed_at', models.DateTimeField(null=True)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='saas_core.providerevent')),
            ],
        ),
        migrations.CreateModel(
            name='SaaSInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('source_key', models.CharField(max_length=180, unique=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('state', models.CharField(choices=[('OPEN', 'OPEN'), ('PAID', 'PAID'), ('VOID', 'VOID')], default='OPEN', max_length=16)),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tax_metadata', models.JSONField(blank=True, default=dict)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saas_invoices', to='academias.academia')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saas_core.commercialsubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('CREATED', 'CREATED'), ('SUBMITTING', 'SUBMITTING'), ('PENDING', 'PENDING'), ('UNKNOWN', 'UNKNOWN'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], default='CREATED', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='saas_core.saasinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('SUBSCRIPTION', 'SUBSCRIPTION'), ('USAGE', 'USAGE'), ('ADJUSTMENT', 'ADJUSTMENT')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('snapshot', models.JSONField(default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='saas_core.saasinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaaSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_reference', models.CharField(max_length=150, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='MANUAL', max_length=20)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='saas_core.saasinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaaSRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('provider_reference', models.CharField(max_length=150, unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.saaspayment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('billable', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=40)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('snapshot', models.JSONField(default=dict)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academias.academia')),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usage', to='eventos.admission')),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saas_core.eventfeerate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.invoiceline')),
                ('usage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='allocation', to='saas_core.usageentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaaSCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academias.academia')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saas_core.saasinvoice')),
                ('usage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saas_core.usageentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version'), name='plan_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='plan_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('interval_months__gte', 1)), name='plan_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('invoice', 'sequence'), name='invoice_attempt_sequence_unique'),
        ),
    ]
