# Generated by Django 5.2.14 on 2026-09-29 04:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0020_commercial_ledger'),
        ('saas_core', '0022_preserve_existing_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialsubscription',
            name='pending_plan_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_subscriptions', to='saas_core.planversion'),
        ),
        migrations.AddField(
            model_name='reportepagosaas',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saas_core.saasinvoice'),
        ),
        migrations.CreateModel(
            name='PaymentMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=150)),
                ('encrypted_token', models.TextField()),
                ('document_type', models.CharField(max_length=10)),
                ('document_number', models.CharField(max_length=50)),
                ('payer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('consent_ip', models.GenericIPAddressField()),
                ('consent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('academia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='academias.academia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
