# Generated by Django 5.2.14 on 2026-09-29 04:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0023_billing_payment_mandate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('academy_name', models.CharField(max_length=150)),
                ('requested_slug', models.SlugField(max_length=100)),
                ('workspace_type', models.CharField(default='ACADEMY', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.planversion')),
            ],
        ),
    ]
