# Generated by Django 6.0.5 on 2026-05-23 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0002_alter_academia_managers'),
        ('planes_estudiantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_egreso', models.CharField(editable=False, help_text='Consecutivo automático (Ej: CE-0001)', max_length=50)),
                ('numero_factura_proveedor', models.CharField(blank=True, help_text='Número de la factura que te dio el proveedor', max_length=100, null=True)),
                ('categoria', models.CharField(choices=[('NOMINA', 'Pago de Profesores / Nómina (Sueldo)'), ('ARRIENDO', 'Arriendo de Sede / Soportes'), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Internet)'), ('MARKETING', 'Publicidad y Marketing'), ('EQUIPOS', 'Mantenimiento o Equipos del salón'), ('OTROS', 'Otros Egresos / Imprevistos')], default='OTROS', max_length=50)),
                ('concepto', models.CharField(help_text='Ej: Pago de 4 clases de Salsa dictadas por el Prof. Carlos', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(help_text='Fecha real del gasto o pago')),
                ('proveedor_nit', models.CharField(help_text='Cédula o NIT del tercero que recibe el dinero', max_length=50)),
                ('proveedor_nombre', models.CharField(help_text='Nombre o Razón Social del tercero', max_length=255)),
                ('soporte_digital', models.FileField(blank=True, help_text='PDF o Foto de la tirilla o factura. (Opcional)', null=True, upload_to='soportes_gastos/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Válido / Activo'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=20)),
                ('motivo_anulacion', models.TextField(blank=True, help_text='Por qué se anuló este egreso', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='academias.academia')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_anulados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReciboIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(editable=False, help_text='Consecutivo automático (Ej: RC-0001)', max_length=50)),
                ('tipo_ingreso', models.CharField(choices=[('PLAN_ESTUDIANTE', 'Pago de Plan / Tiquetera / Mensualidad'), ('TIENDA', 'Venta de Productos (Agua, Ropa, etc.)'), ('EVENTO', 'Venta de Boletas / Inscripción a Eventos'), ('OTROS', 'Otros Ingresos / Arriendos de Salón')], default='PLAN_ESTUDIANTE', max_length=50)),
                ('concepto', models.CharField(help_text='Detalle (Ej: Venta de Camiseta Oficial o Pago Mes Luis Pérez)', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia (Nequi/Daviplata/Bancolombia)'), ('TARJETA', 'Tarjeta de Crédito / Débito')], default='EFECTIVO', max_length=50)),
                ('cliente_nit', models.CharField(help_text='Cédula o NIT de quien paga', max_length=50)),
                ('cliente_nombre', models.CharField(help_text='Nombre de quien realiza el pago', max_length=255)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Válido / Activo'), ('ANULADO', 'Anulado / Sin Efecto Contable')], default='ACTIVO', max_length=20)),
                ('motivo_anulacion', models.TextField(blank=True, help_text='Por qué se anuló este recibo de caja', null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='academias.academia')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_anulados', to=settings.AUTH_USER_MODEL)),
                ('inscripcion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibo_caja', to='planes_estudiantes.inscripcionplan')),
            ],
        ),
    ]
