# Generated by Django 5.2.14 on 2026-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='es_deducible',
            field=models.BooleanField(default=True, help_text='¿Este gasto cuenta con soporte válido para deducir impuestos (DIAN)?'),
        ),
    ]
