# Generated by Django 5.2.14 on 2026-09-04 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_gasto_es_deducible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha real del gasto o pago'),
        ),
        migrations.AlterField(
            model_name='reciboingreso',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reciboingreso',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
