# Generated by Django 5.2.14 on 2026-09-29 04:10

import apps.academias.private_media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_gasto_creado_en_alter_gasto_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='soporte_digital',
            field=models.FileField(blank=True, help_text='PDF o Foto de la tirilla o factura. (Opcional)', null=True, storage=apps.academias.private_media.PrivateStorage(), upload_to='soportes_gastos/', validators=[apps.academias.private_media.validate_private_upload]),
        ),
    ]
