# Generated by Django 6.0.5 on 2026-05-22 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Academia')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Sub-URL / Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_academias/', verbose_name='Logo Oficial')),
                ('color_primario', models.CharField(default='#6f42c1', max_length=7, verbose_name='Color Primario (Hex)')),
                ('color_secundario', models.CharField(default='#e83e8c', max_length=7, verbose_name='Color Secundario (Hex)')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('nit', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT / Identificación Fiscal')),
                ('activo', models.BooleanField(default=True, verbose_name='Cuenta Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN_ACADEMIA', 'Administrador de Academia'), ('PROFESOR', 'Profesor / Instructor'), ('ESTUDIANTE', 'Estudiante (Acceso limitado)')], default='ESTUDIANTE', max_length=20)),
                ('academia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='academias.academia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
