# Generated by Django 6.0.5 on 2026-05-23 00:30

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='academia',
            managers=[
                ('unfiltered_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
