# Generated by Django 6.0.5 on 2026-05-24 20:00

import apps.academias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0002_alter_academia_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='academia',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='academia',
            name='direccion_sede',
            field=models.CharField(default='Distrito Social Cra 29 #68-18', max_length=255, verbose_name='Dirección Física'),
        ),
        migrations.AddField(
            model_name='academia',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de Facebook'),
        ),
        migrations.AddField(
            model_name='academia',
            name='hero_eslogan',
            field=models.CharField(default='Transformamos tu ritmo interno en arte, salud y disciplina.', max_length=255, verbose_name='Subtítulo/Eslogan - Slide 1'),
        ),
        migrations.AddField(
            model_name='academia',
            name='hero_eslogan_2',
            field=models.CharField(default='Explora nuestra agenda de actividades mensuales abajo.', max_length=255, verbose_name='Subtítulo/Eslogan - Slide 2'),
        ),
        migrations.AddField(
            model_name='academia',
            name='hero_imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to=apps.academias.models.ruta_branding_academia, verbose_name='Imagen de Fondo - Slide 1'),
        ),
        migrations.AddField(
            model_name='academia',
            name='hero_imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to=apps.academias.models.ruta_branding_academia, verbose_name='Imagen de Fondo - Slide 2'),
        ),
        migrations.AddField(
            model_name='academia',
            name='hero_titulo',
            field=models.CharField(default='Siente la pasión de bailar', max_length=200, verbose_name='Título Principal - Slide 1'),
        ),
        migrations.AddField(
            model_name='academia',
            name='hero_titulo_2',
            field=models.CharField(default='Talleres Especiales y Eventos Sociales', max_length=200, verbose_name='Título Principal - Slide 2'),
        ),
        migrations.AddField(
            model_name='academia',
            name='horario_atencion',
            field=models.CharField(default='Lun - Sáb: 4:00 PM - 9:00 PM', max_length=150, verbose_name='Horario Comercial'),
        ),
        migrations.AddField(
            model_name='academia',
            name='info_descripcion_1',
            field=models.TextField(default='En nuestra academia nos apasiona guiarte en el viaje del movimiento corporal, rompiendo barreras físicas y mentales.', verbose_name='Párrafo Principal'),
        ),
        migrations.AddField(
            model_name='academia',
            name='info_descripcion_2',
            field=models.TextField(default='Ofrecemos un espacio optimizado de aprendizaje, profesores altamente experimentados y un ecosistema digital integrado.', verbose_name='Párrafo Secundario'),
        ),
        migrations.AddField(
            model_name='academia',
            name='info_titulo',
            field=models.CharField(default='Sobre Nosotros', max_length=150, verbose_name='Título Sección Información'),
        ),
        migrations.AddField(
            model_name='academia',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de Instagram'),
        ),
        migrations.AlterField(
            model_name='academia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
