# Generated by Django 6.0.5 on 2026-05-24 20:02

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0003_alter_academia_managers_academia_direccion_sede_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='academia',
            managers=[
                ('unfiltered_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
