# Generated by Django 6.0.5 on 2026-05-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0004_alter_academia_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL TikTok'),
        ),
        migrations.AddField(
            model_name='academia',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace Directo WhatsApp (ej: https://wa.me/57...)'),
        ),
        migrations.AddField(
            model_name='academia',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL YouTube'),
        ),
        migrations.AlterField(
            model_name='academia',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Facebook'),
        ),
        migrations.AlterField(
            model_name='academia',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Instagram'),
        ),
    ]
