# Generated by Django 6.0.5 on 2026-05-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0005_academia_tiktok_url_academia_whatsapp_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='bloque_1_icono',
            field=models.CharField(default='bi-trophy-fill', max_length=50, verbose_name='Ícono Cuadro 1'),
        ),
        migrations.AddField(
            model_name='academia',
            name='bloque_1_titulo',
            field=models.CharField(default='Alta Competencia', max_length=50, verbose_name='Título Cuadro 1'),
        ),
        migrations.AddField(
            model_name='academia',
            name='bloque_2_icono',
            field=models.CharField(default='bi-heart-pulse-fill', max_length=50, verbose_name='Ícono Cuadro 2'),
        ),
        migrations.AddField(
            model_name='academia',
            name='bloque_2_titulo',
            field=models.CharField(default='Salud & Fitness', max_length=50, verbose_name='Título Cuadro 2'),
        ),
    ]
