# Generated by Django 6.0.5 on 2026-05-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0006_academia_bloque_1_icono_academia_bloque_1_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='bloque_1_icono',
            field=models.CharField(choices=[('bi-music-note-beamed', '🎵 Notas Musicales / Ritmo'), ('bi-music-note', '🎶 Nota Simple / Melodía'), ('bi-disc', '💿 Vinilo / DJ / Social Pista'), ('bi-fire', '🔥 Fuego / Pasión / Coreografía'), ('bi-lightning-charge-fill', '⚡ Rayo / Urbano / Power / Fuerza'), ('bi-heart-pulse-fill', '❤️ Corazón / Salud / Fitness / Bienestar'), ('bi-activity', '📈 Ondas / Progreso / Disciplina'), ('bi-gem', '💎 Diamante / Técnica Pura / Estilo'), ('bi-trophy-fill', '🏆 Trofeo / Alta Competencia / Logros'), ('bi-award-fill', '🥇 Medalla / Certificación / Profesorado'), ('bi-star-fill', '⭐ Estrella / Élite / Factor Diferenciador'), ('bi-people-fill', '👥 Comunidad / Parejas / Clases Grupales'), ('bi-emoji-smile-fill', '😀 Sonrisa / Ambiente Sano / Diversión'), ('bi-geo-alt-fill', '📍 Pin Ubicación / Sedes / Salones'), ('bi-clock-fill', '🕒 Reloj / Horarios Flexibles / Puntualidad'), ('bi-calendar-heart', '📅 Calendario / Eventos / Workshops / Galas'), ('bi-qr-code-scan', '🔍 Escáner QR / Acceso Seguro / Control'), ('bi-shield-check', '🛡️ Escudo / Espacio Seguro / Confianza'), ('bi-phone-vibrate', '📱 Celular / App Alumno / Control Digital'), ('bi-ticket-perforated-fill', '🎫 Ticket / Entrada / Pasarela Online')], default='bi-trophy-fill', max_length=50, verbose_name='Ícono Cuadro 1'),
        ),
        migrations.AlterField(
            model_name='academia',
            name='bloque_2_icono',
            field=models.CharField(choices=[('bi-music-note-beamed', '🎵 Notas Musicales / Ritmo'), ('bi-music-note', '🎶 Nota Simple / Melodía'), ('bi-disc', '💿 Vinilo / DJ / Social Pista'), ('bi-fire', '🔥 Fuego / Pasión / Coreografía'), ('bi-lightning-charge-fill', '⚡ Rayo / Urbano / Power / Fuerza'), ('bi-heart-pulse-fill', '❤️ Corazón / Salud / Fitness / Bienestar'), ('bi-activity', '📈 Ondas / Progreso / Disciplina'), ('bi-gem', '💎 Diamante / Técnica Pura / Estilo'), ('bi-trophy-fill', '🏆 Trofeo / Alta Competencia / Logros'), ('bi-award-fill', '🥇 Medalla / Certificación / Profesorado'), ('bi-star-fill', '⭐ Estrella / Élite / Factor Diferenciador'), ('bi-people-fill', '👥 Comunidad / Parejas / Clases Grupales'), ('bi-emoji-smile-fill', '😀 Sonrisa / Ambiente Sano / Diversión'), ('bi-geo-alt-fill', '📍 Pin Ubicación / Sedes / Salones'), ('bi-clock-fill', '🕒 Reloj / Horarios Flexibles / Puntualidad'), ('bi-calendar-heart', '📅 Calendario / Eventos / Workshops / Galas'), ('bi-qr-code-scan', '🔍 Escáner QR / Acceso Seguro / Control'), ('bi-shield-check', '🛡️ Escudo / Espacio Seguro / Confianza'), ('bi-phone-vibrate', '📱 Celular / App Alumno / Control Digital'), ('bi-ticket-perforated-fill', '🎫 Ticket / Entrada / Pasarela Online')], default='bi-heart-pulse-fill', max_length=50, verbose_name='Ícono Cuadro 2'),
        ),
    ]
