# Generated by Django 6.0.5 on 2026-05-24 21:21

import apps.academias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0007_alter_academia_bloque_1_icono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='bloque_3_icono',
            field=models.CharField(blank=True, choices=[('bi-music-note-beamed', '🎵 Notas Musicales / Ritmo'), ('bi-music-note', '🎶 Nota Simple / Melodía'), ('bi-disc', '💿 Vinilo / DJ / Social Pista'), ('bi-fire', '🔥 Fuego / Pasión / Coreografía'), ('bi-lightning-charge-fill', '⚡ Rayo / Urbano / Power / Fuerza'), ('bi-heart-pulse-fill', '❤️ Corazón / Salud / Fitness / Bienestar'), ('bi-activity', '📈 Ondas / Progreso / Disciplina'), ('bi-gem', '💎 Diamante / Técnica Pura / Estilo'), ('bi-trophy-fill', '🏆 Trofeo / Alta Competencia / Logros'), ('bi-award-fill', '🥇 Medalla / Certificación / Profesorado'), ('bi-star-fill', '⭐ Estrella / Élite / Factor Diferenciador'), ('bi-people-fill', '👥 Comunidad / Parejas / Clases Grupales'), ('bi-emoji-smile-fill', '😀 Sonrisa / Ambiente Sano / Diversión'), ('bi-geo-alt-fill', '📍 Pin Ubicación / Sedes / Salones'), ('bi-clock-fill', '🕒 Reloj / Horarios Flexibles / Puntualidad'), ('bi-calendar-heart', '📅 Calendario / Eventos / Workshops / Galas'), ('bi-qr-code-scan', '🔍 Escáner QR / Acceso Seguro / Control'), ('bi-shield-check', '🛡️ Escudo / Espacio Seguro / Confianza'), ('bi-phone-vibrate', '📱 Celular / App Alumno / Control Digital'), ('bi-ticket-perforated-fill', '🎫 Ticket / Entrada / Pasarela Online')], default='bi-award-fill', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academia',
            name='bloque_3_titulo',
            field=models.CharField(blank=True, default='Instructores de Élite', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academia',
            name='bloque_4_icono',
            field=models.CharField(blank=True, choices=[('bi-music-note-beamed', '🎵 Notas Musicales / Ritmo'), ('bi-music-note', '🎶 Nota Simple / Melodía'), ('bi-disc', '💿 Vinilo / DJ / Social Pista'), ('bi-fire', '🔥 Fuego / Pasión / Coreografía'), ('bi-lightning-charge-fill', '⚡ Rayo / Urbano / Power / Fuerza'), ('bi-heart-pulse-fill', '❤️ Corazón / Salud / Fitness / Bienestar'), ('bi-activity', '📈 Ondas / Progreso / Disciplina'), ('bi-gem', '💎 Diamante / Técnica Pura / Estilo'), ('bi-trophy-fill', '🏆 Trofeo / Alta Competencia / Logros'), ('bi-award-fill', '🥇 Medalla / Certificación / Profesorado'), ('bi-star-fill', '⭐ Estrella / Élite / Factor Diferenciador'), ('bi-people-fill', '👥 Comunidad / Parejas / Clases Grupales'), ('bi-emoji-smile-fill', '😀 Sonrisa / Ambiente Sano / Diversión'), ('bi-geo-alt-fill', '📍 Pin Ubicación / Sedes / Salones'), ('bi-clock-fill', '🕒 Reloj / Horarios Flexibles / Puntualidad'), ('bi-calendar-heart', '📅 Calendario / Eventos / Workshops / Galas'), ('bi-qr-code-scan', '🔍 Escáner QR / Acceso Seguro / Control'), ('bi-shield-check', '🛡️ Escudo / Espacio Seguro / Confianza'), ('bi-phone-vibrate', '📱 Celular / App Alumno / Control Digital'), ('bi-ticket-perforated-fill', '🎫 Ticket / Entrada / Pasarela Online')], default='bi-qr-code-scan', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academia',
            name='bloque_4_titulo',
            field=models.CharField(blank=True, default='Ecosistema Digital QR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academia',
            name='info_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.academias.models.ruta_branding_academia, verbose_name='Imagen de la Sede/Equipo'),
        ),
        migrations.AlterField(
            model_name='academia',
            name='info_descripcion_1',
            field=models.TextField(default='En nuestra academia nos apasiona guiarte en el viaje del movimiento corporal, rompiendo barreras físicas y mentales.'),
        ),
        migrations.AlterField(
            model_name='academia',
            name='info_descripcion_2',
            field=models.TextField(default='Ofrecemos un espacio optimizado de aprendizaje, profesores altamente experimentados y un ecosistema digital integrado.'),
        ),
        migrations.AlterField(
            model_name='academia',
            name='info_titulo',
            field=models.CharField(default='Sobre Nosotros', max_length=150),
        ),
    ]
