# Generated by Django 6.0.5 on 2026-05-24 21:50

import apps.academias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0008_academia_bloque_3_icono_academia_bloque_3_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='login_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.academias.models.ruta_branding_academia, verbose_name='Imagen de Fondo Login'),
        ),
        migrations.AlterField(
            model_name='academia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.academias.models.ruta_branding_academia, verbose_name='Logo Oficial'),
        ),
        migrations.AlterField(
            model_name='academia',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace Directo WhatsApp'),
        ),
    ]
