# Generated by Django 6.0.5 on 2026-05-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0009_academia_login_imagen_alter_academia_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='academia',
            managers=[
            ],
        ),
    ]
