# Generated by Django 6.0.5 on 2026-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0010_alter_academia_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='divisa',
            field=models.CharField(default='COP', max_length=3, verbose_name='Divisa de Operación'),
        ),
        migrations.AddField(
            model_name='academia',
            name='forzar_stripe_fuera_de_radar',
            field=models.BooleanField(default=False, verbose_name='Forzar Stripe (Cuenta Internacional/Atlas)'),
        ),
        migrations.AddField(
            model_name='academia',
            name='pais',
            field=models.CharField(choices=[('CO', 'Colombia 🇨🇴 (COP)'), ('US', 'Estados Unidos 🇺🇸 (USD)'), ('ES', 'España 🇪🇸 (EUR)'), ('MX', 'México 🇲🇽 (MXN)'), ('CL', 'Chile 🇨🇱 (CLP)'), ('BR', 'Brasil 🇧🇷 (BRL)'), ('PE', 'Perú 🇵🇪 (PEN)'), ('OT', 'Otro País (Soporte Especial / USD)')], default='CO', max_length=2, verbose_name='País de Operación'),
        ),
        migrations.AddField(
            model_name='academia',
            name='payu_account_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PayU Account ID'),
        ),
        migrations.AddField(
            model_name='academia',
            name='payu_api_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PayU API Key'),
        ),
        migrations.AddField(
            model_name='academia',
            name='payu_merchant_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PayU Merchant ID'),
        ),
        migrations.AddField(
            model_name='academia',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Stripe Public Key'),
        ),
        migrations.AddField(
            model_name='academia',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Stripe Secret Key'),
        ),
        migrations.AddField(
            model_name='academia',
            name='tarjeta_respaldo_configurada',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Tarjeta de Respaldo Habilitada?'),
        ),
    ]
