# Generated by Django 6.0.5 on 2026-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0011_academia_divisa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='template_landing_personalizado',
            field=models.CharField(blank=True, help_text='Ej: academias/landings/duane_aleja.html. Si se deja vacío, usará el index estándar.', max_length=100, null=True),
        ),
    ]
