# Generated by Django 6.0.5 on 2026-05-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0012_academia_template_landing_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='es_solo_eventos',
            field=models.BooleanField(default=False, help_text='Activa esto si la organización no da clases regulares y solo usa el sistema para vender tickets de eventos/festivales.', verbose_name='Modo Productora de Eventos'),
        ),
    ]
