# Generated by Django 5.2.14 on 2026-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0013_academia_es_solo_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social (Legal)'),
        ),
        migrations.AddField(
            model_name='academia',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='academia',
            name='resolucion_facturacion',
            field=models.TextField(blank=True, help_text='Texto legal corto que aparecerá en el pie del PDF de la cuenta de cobro.', null=True),
        ),
        migrations.AddField(
            model_name='academia',
            name='tipo_regimen',
            field=models.CharField(blank=True, default='No responsable de IVA', max_length=100, null=True, verbose_name='Régimen Fiscal (Ej: Régimen Simple, Responsable de IVA)'),
        ),
    ]
