# Generated by Django 5.2.14 on 2026-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0014_academia_razon_social_academia_representante_legal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Bogotá', 'Bogotá'), ('Medellín', 'Medellín'), ('Cali', 'Cali'), ('Barranquilla', 'Barranquilla'), ('Bucaramanga', 'Bucaramanga'), ('Pereira', 'Pereira'), ('Manizales', 'Manizales'), ('Armenia', 'Armenia'), ('Cartagena', 'Cartagena'), ('Villavicencio', 'Villavicencio'), ('Ibagué', 'Ibagué'), ('Otra', 'Otra ciudad...')], default='Bogotá', max_length=50, null=True, verbose_name='Ciudad Principal'),
        ),
    ]
