# Generated by Django 5.2.14 on 2026-08-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0015_academia_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academia',
            name='whatsapp_url',
        ),
        migrations.AddField(
            model_name='academia',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Ej: 573001234567 (Incluye el código de país, sin el símbolo +)', max_length=25, null=True, verbose_name='Número de WhatsApp'),
        ),
    ]
