# Generated by Django 5.2.14 on 2026-09-29 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0016_remove_academia_whatsapp_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Propietario'), ('ADMIN', 'Administrador'), ('TEACHER', 'Profesor'), ('STUDENT', 'Estudiante'), ('BILLING', 'Facturación')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='MANUAL', max_length=32)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='academias.academia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'academia'), name='membership_user_academy_unique')],
            },
        ),
    ]
