# Generated by Django 5.2.14 on 2026-09-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0019_account_setup_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='workspace_type',
            field=models.CharField(choices=[('ACADEMY', 'Academia'), ('EVENT_ORGANIZER', 'Organizador de eventos'), ('INTERNAL', 'Interno')], default='ACADEMY', max_length=20),
        ),
    ]
