# Generated by Django 5.2.14 on 2026-07-23 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0014_academia_razon_social_academia_representante_legal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=False, verbose_name='¿Asistió realmente a la clase?')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada (Visible para reservar)'), ('DICTADA', 'Dictada (Check del Admin)'), ('CANCELADA', 'Cancelada (Nadie puede reservar)')], default='PROGRAMADA', max_length=20)),
                ('pagada_al_profesor', models.BooleanField(default=False, verbose_name='¿Ya se le pagó al profesor?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Clase')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tarifa_especifica', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar en blanco para usar la tarifa base del profesor.', max_digits=10, null=True)),
                ('color_calendario', models.CharField(default='#6f42c1', help_text='Color HEX para el calendario', max_length=7)),
                ('limite_cupos', models.IntegerField(default=30, verbose_name='Cupo máximo de estudiantes')),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academias.academia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
