# Generated by Django 5.2.14 on 2026-07-23 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0014_academia_razon_social_academia_representante_legal_and_more'),
        ('calendario', '0001_initial'),
        ('finanzas', '0002_gasto_es_deducible'),
        ('profesores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='profesor_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_plantilla', to='profesores.profesor'),
        ),
        migrations.AddField(
            model_name='reservaestudiante',
            name='academia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academias.academia'),
        ),
        migrations.AddField(
            model_name='reservaestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='academia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academias.academia'),
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='calendario.clase'),
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='gasto_individual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesion_individual', to='finanzas.gasto'),
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='orden_pago_mensual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_incluidas', to='profesores.ordenpagomensual'),
        ),
        migrations.AddField(
            model_name='reservaestudiante',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='calendario.sesionclase'),
        ),
        migrations.AlterUniqueTogether(
            name='reservaestudiante',
            unique_together={('sesion', 'estudiante')},
        ),
    ]
