# Generated by Django 5.2.14 on 2026-07-23 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_initial'),
        ('finanzas', '0002_gasto_es_deducible'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si se desactiva, dejarán de generarse sesiones futuras.'),
        ),
        migrations.AddField(
            model_name='clase',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0, verbose_name='Día de la semana'),
        ),
        migrations.AddField(
            model_name='clase',
            name='hora_fin',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clase',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='notas_excepcion',
            field=models.CharField(blank=True, help_text='Ej: Clase especial enfocada en musicalidad.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='profesor_reemplazo',
            field=models.ForeignKey(blank=True, help_text='Profesor invitado o reemplazo solo por este día.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_reemplazo', to='profesores.profesor'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='color_calendario',
            field=models.CharField(default='#6f42c1', max_length=7),
        ),
        migrations.AlterField(
            model_name='clase',
            name='limite_cupos',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de la Clase (Ej: Bachata Principiantes)'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='tarifa_especifica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sesionclase',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada (Visible para reservar)'), ('DICTADA', 'Dictada (Check del Admin)'), ('CANCELADA', 'Cancelada (Feriado, ausencia, etc)')], default='PROGRAMADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='sesionclase',
            name='gasto_individual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.gasto'),
        ),
        migrations.AlterField(
            model_name='sesionclase',
            name='orden_pago_mensual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesores.ordenpagomensual'),
        ),
        migrations.AlterField(
            model_name='sesionclase',
            name='pagada_al_profesor',
            field=models.BooleanField(default=False),
        ),
    ]
