# Generated by Django 5.2.14 on 2026-07-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_clase_activa_clase_dia_semana_clase_hora_fin_and_more'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='profesor_asignado',
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='profesor_asignado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_asignadas', to='profesores.profesor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de la Clase'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='tarifa_especifica',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Déjalo en blanco para usar la tarifa base del profesor que la dicte.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sesionclase',
            name='notas_excepcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
