# Generated by Django 5.2.14 on 2026-09-29 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_remove_clase_activa_remove_clase_dia_semana_and_more'),
        ('planes_estudiantes', '0005_atomic_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaestudiante',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservaestudiante',
            name='charged_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charged_reservations', to='planes_estudiantes.inscripcionplan'),
        ),
    ]
