# Generated by Django 5.2.14 on 2026-06-04 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0013_academia_es_solo_eventos'),
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_tienda', to='academias.academia')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'unique_together': {('academia', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_barras', models.CharField(blank=True, help_text='Opcional: Para escáner o referencia rápida', max_length=100, null=True)),
                ('precio_compra_actual', models.DecimalField(decimal_places=2, help_text='Costo para la academia', max_digits=10)),
                ('precio_venta_actual', models.DecimalField(decimal_places=2, help_text='Precio para el alumno', max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5, help_text='Para alertar cuando se esté acabando')),
                ('estado', models.BooleanField(default=True, help_text='Desmarcar para ocultar del POS si ya no se vende')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='academias.academia')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='tienda.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='A cómo se compró esta vez', max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='VentaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_tienda', to='academias.academia')),
                ('recibo_caja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_origen', to='finanzas.reciboingreso')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('ganancia', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.ventatienda')),
            ],
        ),
    ]
