# Generated by Django 5.2.14 on 2026-09-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatienda',
            name='request_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ventatienda',
            name='request_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
