"""
Django settings for gestoracademia project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 🚀 TRUCO SENIOR: Añadir el directorio 'apps' al sys.path para importar limpio
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u0b_7m(ed_=+w#z8u)z=hpvtrjf^8*d(#x9fsdfn+*=(y$p63&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
ENTORNO_PRODUCCION = os.environ.get('DJANGO_ENV') == 'production'

if ENTORNO_PRODUCCION:
    # 🌍 MODO PRODUCCIÓN (PYTHONANYWHERE)
    DEBUG = False
    ALLOWED_HOSTS = ['appdanza.com', 'www.appdanza.com', 'webapp-3085879.pythonanywhere.com']
    
    # Cloudflare usa HTTPS, necesitamos decirle a Django que confíe en el origen
    CSRF_TRUSTED_ORIGINS = ['https://appdanza.com', 'https://www.appdanza.com']
    
    # Seguridad estricta activada
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    # 💻 MODO DESARROLLO (TU PC LOCAL)
    DEBUG = True
    ALLOWED_HOSTS = ['*']
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'academias',
    'planes_estudiantes',
    'asistencias',
    'finanzas',
    'eventos',
    'multimedia',
    "csp",
    'saas_core',
    'tienda',
]

MIDDLEWARE = [
    "csp.middleware.CSPMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'gestoracademia.middleware.TenantMiddleware',
    
]

ROOT_URLCONF = 'gestoracademia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestoracademia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'



SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

############################################################
# CSP DJANGO-CSP 4.x
############################################################

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {

        "default-src": (
            "'self'",
        ),

        ####################################################
        # SCRIPTS
        ####################################################
        "script-src": (
            "'self'",
            "'unsafe-inline'",
            "'unsafe-eval'",
            "https://accounts.google.com",
            "https://apis.google.com",
            "https://www.youtube.com",      # <-- PERMITIDO: JS del reproductor de YouTube
            "https://s.ytimg.com",          # <-- PERMITIDO: Assets estáticos de YouTube (reproductor)
            "https://cdn.jsdelivr.net",
            "https://static.cloudflareinsights.com",
            "https://code.jquery.com",
            "https://cdn.datatables.net",
            "https://unpkg.com",

        ),

        ####################################################
        # ESTILOS
        ####################################################
        "style-src": (
            "'self'",
            "'unsafe-inline'",
            "https://cdn.jsdelivr.net",
            "https://fonts.googleapis.com",
            "https://cdn.datatables.net",
        ),

        ####################################################
        # FUENTES
        ####################################################
        "font-src": (
            "'self'",
            "data:",
            "https://cdn.jsdelivr.net",
            "https://fonts.gstatic.com",
        ),

        ####################################################
        # CONEXIONES
        ####################################################
        "connect-src": (
            "'self'",
            "https://accounts.google.com",
            "https://www.googleapis.com",
            "https://youtube.googleapis.com",
            "https://cdn.jsdelivr.net",
            "https://cloudflareinsights.com",
        ),

        ####################################################
        # IFRAMES (Aquí estaba el bloqueo principal)
        ####################################################
        "frame-src": (
            "'self'",
            "https://accounts.google.com",
            "https://www.youtube.com",          # <-- SOLUCIÓN: Permite el iframe tradicional
            "https://www.youtube-nocookie.com", # <-- RECOMENDACIÓN: Por si usas el modo privacidad mejorada
        ),

        ####################################################
        # IMÁGENES
        ####################################################
        "img-src": (
            "'self'",
            "data:",
            "blob:",
            "https://*.googleusercontent.com",
            "https://i.ytimg.com",             # <-- OPTIONAL: Si luego quieres mostrar miniaturas de YouTube en el SaaS
        ),

        ####################################################
        # OBJECT
        ####################################################
        "object-src": (
            "'none'",
        ),
    }
}




# Evita que scripts maliciosos de una subruta lean cookies de otra
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True



# Controla el comportamiento de las cookies en el mismo sitio
SESSION_COOKIE_SAMESITE = 'Lax'