"""
Django settings for gestoracademia project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 🚀 TRUCO SENIOR: Añadir el directorio 'apps' al sys.path para importar limpio
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Credentials belong to AppDanza's own merchant. No fallback to DyA settings.
APPDANZA_PUBLIC_URL = os.getenv('APPDANZA_PUBLIC_URL', 'https://appdanza.com')
APPDANZA_EPAYCO_PUBLIC_KEY = os.getenv('APPDANZA_EPAYCO_PUBLIC_KEY', '')
APPDANZA_EPAYCO_PRIVATE_KEY = os.getenv('APPDANZA_EPAYCO_PRIVATE_KEY', '')
APPDANZA_EPAYCO_CUSTOMER_ID = os.getenv('APPDANZA_EPAYCO_CUSTOMER_ID', '')
APPDANZA_EPAYCO_P_KEY = os.getenv('APPDANZA_EPAYCO_P_KEY', '')
APPDANZA_EPAYCO_TEST = os.getenv('APPDANZA_EPAYCO_TEST', 'true').lower() == 'true'
APPDANZA_EPAYCO_LIVE_ENABLED = os.getenv('APPDANZA_EPAYCO_LIVE_ENABLED', 'false').lower() == 'true'
APPDANZA_AUTOMATIC_BILLING_ENABLED = os.getenv('APPDANZA_AUTOMATIC_BILLING_ENABLED', 'false').lower() == 'true'
APPDANZA_TOKEN_ENCRYPTION_KEY = os.getenv('APPDANZA_TOKEN_ENCRYPTION_KEY', '')
APPDANZA_PILOT_TRIAL_DAYS = int(os.getenv('APPDANZA_PILOT_TRIAL_DAYS', '14'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
ENTORNO_PRODUCCION = os.environ.get('DJANGO_ENV') == 'production'

if ENTORNO_PRODUCCION:
    # 🌍 MODO PRODUCCIÓN (PYTHONANYWHERE)
    DEBUG = os.getenv('DEBUG', 'False') == 'True'
    ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
    
    # Cloudflare usa HTTPS, necesitamos decirle a Django que confíe en el origen
    CSRF_TRUSTED_ORIGINS = ['https://appdanza.com', 'https://www.appdanza.com']
    
    # Seguridad estricta activada
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    # 💻 MODO DESARROLLO (TU PC LOCAL)
    DEBUG = True
    ALLOWED_HOSTS = ['*']
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.academias',
    'apps.planes_estudiantes',
    'apps.asistencias',
    'apps.finanzas',
    'apps.eventos',
    'apps.multimedia',
    "csp",
    'apps.saas_core',
    'apps.tienda',
    'apps.comunicaciones',
    'apps.profesores',
    'apps.calendario',
]

MIDDLEWARE = [
    "csp.middleware.CSPMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'gestoracademia.middleware.TenantMiddleware',
    'apps.academias.access_middleware.TenantAuthorizationMiddleware',
    
]

ROOT_URLCONF = 'gestoracademia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestoracademia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.getenv('APPDANZA_SQLITE_PATH', str(BASE_DIR / 'db.sqlite3')),
        # Serialize short write transactions before their first read. No
        # ATOMIC_REQUESTS: provider I/O remains outside database transactions.
        'OPTIONS': {'timeout': 20, 'transaction_mode': 'IMMEDIATE'},
        'TEST': {'NAME': os.getenv('APPDANZA_TEST_DB') or None},
    }
}
if os.getenv('APPDANZA_DB_ENGINE', 'sqlite') == 'postgresql':
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['APPDANZA_DB_NAME'],
        'USER': os.environ['APPDANZA_DB_USER'],
        'PASSWORD': os.environ['APPDANZA_DB_PASSWORD'],
        'HOST': os.environ['APPDANZA_DB_HOST'],
        'PORT': os.getenv('APPDANZA_DB_PORT', '5432'),
        'CONN_MAX_AGE': 0,
        'OPTIONS': {'sslmode': os.getenv('APPDANZA_DB_SSLMODE', 'require'), 'connect_timeout': 10},
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'



SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

############################################################
# CSP DJANGO-CSP 4.x
############################################################

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {

        "default-src": (
            "'self'",
        ),

        ####################################################
        # SCRIPTS
        ####################################################
        "script-src": (
            "'self'",
            "'unsafe-inline'",
            "'unsafe-eval'",
            "https://accounts.google.com",
            "https://apis.google.com",
            "https://www.youtube.com",      # <-- PERMITIDO: JS del reproductor de YouTube
            "https://s.ytimg.com",          # <-- PERMITIDO: Assets estáticos de YouTube (reproductor)
            "https://cdn.jsdelivr.net",
            "https://static.cloudflareinsights.com",
            "https://code.jquery.com",
            "https://checkout.epayco.co",
            "https://cdn.datatables.net",
            "https://unpkg.com",

        ),

        ####################################################
        # ESTILOS
        ####################################################
        "style-src": (
            "'self'",
            "'unsafe-inline'",
            "https://cdn.jsdelivr.net",
            "https://fonts.googleapis.com",
            "https://cdn.datatables.net",
        ),

        ####################################################
        # FUENTES
        ####################################################
        "font-src": (
            "'self'",
            "data:",
            "https://cdn.jsdelivr.net",
            "https://fonts.gstatic.com",
        ),

        ####################################################
        # CONEXIONES
        ####################################################
        "connect-src": (
            "https://api.secure.payco.co",
            "'self'",
            "https://accounts.google.com",
            "https://www.googleapis.com",
            "https://youtube.googleapis.com",
            "https://cdn.jsdelivr.net",
            "https://cloudflareinsights.com",
        ),

        ####################################################
        # IFRAMES (Aquí estaba el bloqueo principal)
        ####################################################
        "frame-src": (
            "'self'",
            "https://accounts.google.com",
            "https://www.youtube.com",          # <-- SOLUCIÓN: Permite el iframe tradicional
            "https://www.youtube-nocookie.com", # <-- RECOMENDACIÓN: Por si usas el modo privacidad mejorada
        ),

        ####################################################
        # IMÁGENES
        ####################################################
        "img-src": (
            "'self'",
            "data:",
            "blob:",
            "https://*.googleusercontent.com",
            "https://i.ytimg.com",             # <-- OPTIONAL: Si luego quieres mostrar miniaturas de YouTube en el SaaS
        ),

        ####################################################
        # OBJECT
        ####################################################
        "object-src": (
            "'none'",
        ),
    }
}




# Evita que scripts maliciosos de una subruta lean cookies de otra
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True



# Controla el comportamiento de las cookies en el mismo sitio
SESSION_COOKIE_SAMESITE = 'Lax'


# ==========================================
# CONFIGURACIÓN DE CORREOS (GMAIL SMTP)
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('SMTP_USER') # Reemplaza con el correo de tu SaaS
EMAIL_HOST_PASSWORD = os.getenv('SMTP_PASSWORD') # 🚨 Mejor si usas os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('SMTP_DEFAULT') # Nombre visible



LOGIN_URL = 'academias:login' 

# A dónde va el usuario si hace login directo sin un link previo
LOGIN_REDIRECT_URL = '/' 

# A dónde va el usuario al cerrar sesión
LOGOUT_REDIRECT_URL = 'login'
# Private read-only Bachatamania integration. Empty token disables access.
DYA_INTEGRATION_API_TOKEN = os.getenv('DYA_INTEGRATION_API_TOKEN', '').strip()
